import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/app/components/nav-bar";
import { AuthProvider } from "@/app/context/auth";

const inter = Inter({ subsets: ["latin"] });

// header
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <AuthProvider>
      <NavBar/>
      {children}
    </AuthProvider>
    </body>
    </html>
  );
}
