## api auth register1
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
  "username": "phasetr",
  "email": "phasetr@gmail.com",
  "password": "phasetr"
}

###
## api auth register2
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
"username": "phasetr2",
"email": "phasetr+added@gmail.com",
"password": "phasetr2"
}

###
## api auth login
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "email": "phasetr@gmail.com",
  "password": "phasetr"
}
