import "./globals.css";
import { Inter } from "next/font/google";
import React from "react";
import NavBar from "@/app/components/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode
  }) {
  return (
    <html lang="ja">
    <body className={inter.className}>
    <NavBar/>
    {children}</body>
    </html>
  );
}
