name = "nextapp"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

main = "src/index.js"

[[d1_databases]]
binding = "DB"
database_name = "numbers-db"
database_id = "placeholder-db-id"
migrations_dir = "drizzle"