name = "pnpm-e2e-web"
main = "./dist/_worker.js"
compatibility_date = "2025-07-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ptdev"
database_id = "ptdev"
migrations_dir = "../core/migrations"
