import "./globals.css";
import React from "react";

export const metadata = {
  title: "e2e lesson",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
    <body>{children}</body>
    </html>
  );
}
